toc = [
    # Chapter 1
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "Introduction", "subchapter_code": "1.1"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "The nature of research", "subchapter_code": "1.2"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "Business and management research", "subchapter_code": "1.3"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "The research process", "subchapter_code": "1.4"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "Keeping a reflective diary or research notebook", "subchapter_code": "1.5"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "The purpose and structure of this book", "subchapter_code": "1.6"},
    {"chapter_title": "Research, reflective diaries and the purpose of this book", "subchapter_title": "Summary", "subchapter_code": "1.7"},

    # Chapter 2
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Introduction", "subchapter_code": "2.1"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Characteristics of good research ideas", "subchapter_code": "2.2"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Generating research ideas", "subchapter_code": "2.3"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Refining research ideas", "subchapter_code": "2.4"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Developing your overarching research question", "subchapter_code": "2.5"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Writing a research aim and set of research objectives", "subchapter_code": "2.6"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "The importance of theory", "subchapter_code": "2.7"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "The need for a research proposal", "subchapter_code": "2.8"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Structuring your research proposal", "subchapter_code": "2.9"},
    {"chapter_title": "Generating a research idea and developing your research proposal", "subchapter_title": "Summary", "subchapter_code": "2.10"},

    # Chapter 3
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Introduction", "subchapter_code": "3.1"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Being ‘critical’ and the purposes and forms of review", "subchapter_code": "3.2"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "The content and structure of a critical review", "subchapter_code": "3.3"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Literature sources", "subchapter_code": "3.4"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Planning your literature search", "subchapter_code": "3.5"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Conducting your literature search", "subchapter_code": "3.6"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Reading critically and evaluating the literature", "subchapter_code": "3.7"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Note-taking and referencing", "subchapter_code": "3.8"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Using systematic review", "subchapter_code": "3.9"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Drafting the critical review", "subchapter_code": "3.10"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "A note about plagiarism", "subchapter_code": "3.11"},
    {"chapter_title": "Critically reviewing the literature", "subchapter_title": "Summary", "subchapter_code": "3.12"},

    # Chapter 4
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "Introduction", "subchapter_code": "4.1"},
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "The philosophical underpinnings of business and management", "subchapter_code": "4.2"},
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "Research paradigms", "subchapter_code": "4.3"},
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "Five management philosophies", "subchapter_code": "4.4"},
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "Approaches to theory development", "subchapter_code": "4.5"},
    {"chapter_title": "Understanding research philosophy and approaches to theory development", "subchapter_title": "Summary", "subchapter_code": "4.6"},

    # Chapter 5
    {"chapter_title": "Formulating the research design", "subchapter_title": "Introduction", "subchapter_code": "5.1"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Achieving a coherent research design", "subchapter_code": "5.2"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "The research purpose", "subchapter_code": "5.3"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Methodological choice: choosing a quantitative, qualitative or mixed methods research design", "subchapter_code": "5.4"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Developing a coherent research strategy", "subchapter_code": "5.5"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Considering time horizons", "subchapter_code": "5.6"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Anticipating potential ethical issues", "subchapter_code": "5.7"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Assessing the quality of research design", "subchapter_code": "5.8"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Recognising your role as researcher", "subchapter_code": "5.9"},
    {"chapter_title": "Formulating the research design", "subchapter_title": "Summary", "subchapter_code": "5.10"},

    # Chapter 6
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Introduction", "subchapter_code": "6.1"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Characteristics of access", "subchapter_code": "6.2"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Researcher status", "subchapter_code": "6.3"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Internet-mediated access", "subchapter_code": "6.4"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Strategies to gain access", "subchapter_code": "6.5"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Research ethics and acting ethically", "subchapter_code": "6.6"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Ethical issues at specific research stages", "subchapter_code": "6.7"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Data protection principles", "subchapter_code": "6.8"},
    {"chapter_title": "Negotiating access and research ethics", "subchapter_title": "Summary", "subchapter_code": "6.9"},

    # Chapter 7
    {"chapter_title": "Selecting samples", "subchapter_title": "Introduction", "subchapter_code": "7.1"},
    {"chapter_title": "Selecting samples", "subchapter_title": "The need to sample", "subchapter_code": "7.2"},
    {"chapter_title": "Selecting samples", "subchapter_title": "An overview of sampling procedures", "subchapter_code": "7.3"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Probability sampling – sampling frame", "subchapter_code": "7.4"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Probability sampling – sample size", "subchapter_code": "7.5"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Probability sampling – procedures", "subchapter_code": "7.6"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Probability sampling – representativeness", "subchapter_code": "7.7"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Non-probability sampling – sample size", "subchapter_code": "7.8"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Non-probability sampling – procedures", "subchapter_code": "7.9"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Mixed and multi-stage sampling designs", "subchapter_code": "7.10"},
    {"chapter_title": "Selecting samples", "subchapter_title": "Summary", "subchapter_code": "7.11"},

    # Chapter 8
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Introduction", "subchapter_code": "8.1"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Types of secondary data and uses in research", "subchapter_code": "8.2"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Advantages of secondary data", "subchapter_code": "8.3"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Disadvantages of secondary data", "subchapter_code": "8.4"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Searching for and locating secondary data", "subchapter_code": "8.5"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Evaluating and selecting secondary data sources", "subchapter_code": "8.6"},
    {"chapter_title": "Obtaining and evaluating secondary data", "subchapter_title": "Summary", "subchapter_code": "8.7"},

    # Chapter 9
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Introduction", "subchapter_code": "9.1"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Observation choices", "subchapter_code": "9.2"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Participant observation", "subchapter_code": "9.3"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Structured observation", "subchapter_code": "9.4"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Internet-mediated observation", "subchapter_code": "9.5"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Recording video", "subchapter_code": "9.6"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Creating static images", "subchapter_code": "9.7"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Audio recording", "subchapter_code": "9.8"},
    {"chapter_title": "Collecting primary data using observation", "subchapter_title": "Summary", "subchapter_code": "9.9"},

    # Chapter 10
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Introduction", "subchapter_code": "10.1"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Standardisation and structure in questioning", "subchapter_code": "10.2"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Interview mediums and modes", "subchapter_code": "10.3"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "The potential of semi-structured and in-depth interviews", "subchapter_code": "10.4"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Data quality issues and evaluating interviewing practice", "subchapter_code": "10.5"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Preparing for semi-structured or in-depth interviewing", "subchapter_code": "10.6"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Conducting one-to-one face-to-face interviews", "subchapter_code": "10.7"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Conducting one-to-one online interviews", "subchapter_code": "10.8"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Conducting one-to-one telephone interviews", "subchapter_code": "10.9"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Conducting group interviews and focus groups", "subchapter_code": "10.10"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Conducting visual interviews", "subchapter_code": "10.11"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Using diaries and diary studies", "subchapter_code": "10.12"},
    {"chapter_title": "Collecting primary data using interviews and diaries", "subchapter_title": "Summary", "subchapter_code": "10.13"},

    # Chapter 11
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Introduction", "subchapter_code": "11.1"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Questionnaires: an overview", "subchapter_code": "11.2"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Deciding what data need to be collected", "subchapter_code": "11.3"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Questionnaire validity and reliability", "subchapter_code": "11.4"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Designing individual questions", "subchapter_code": "11.5"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Designing the questionnaire", "subchapter_code": "11.6"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Pilot testing", "subchapter_code": "11.7"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Distributing the questionnaire", "subchapter_code": "11.8"},
    {"chapter_title": "Collecting primary data using questionnaires", "subchapter_title": "Summary", "subchapter_code": "11.9"},

    # Chapter 12
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Introduction", "subchapter_code": "12.1"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Data types and precision of measurement", "subchapter_code": "12.2"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Preparing data for quantitative analysis", "subchapter_code": "12.3"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Data entry and checking", "subchapter_code": "12.4"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Exploring and presenting data: an overview", "subchapter_code": "12.5"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Exploring and presenting individual variables", "subchapter_code": "12.6"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Exploring and comparing two or more variables", "subchapter_code": "12.7"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Describing data using statistics", "subchapter_code": "12.8"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Statistical tests’ assumptions and hypothesis testing", "subchapter_code": "12.9"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Examining associations and differences", "subchapter_code": "12.10"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Assessing the strength of relationships", "subchapter_code": "12.11"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Making predictions", "subchapter_code": "12.12"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Examining trends", "subchapter_code": "12.13"},
    {"chapter_title": "Analysing data quantitatively", "subchapter_title": "Summary", "subchapter_code": "12.14"},

    # Chapter 13
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Introduction", "subchapter_code": "13.1"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Analysing qualitative data, diversity and interactive processes", "subchapter_code": "13.2"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Choosing a qualitative analysis technique", "subchapter_code": "13.3"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Preparing data for analysis", "subchapter_code": "13.4"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Aids to help analysis", "subchapter_code": "13.5"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Thematic Analysis", "subchapter_code": "13.6"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Template Analysis", "subchapter_code": "13.7"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Explanation Building and Testing", "subchapter_code": "13.8"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Grounded Theory Method", "subchapter_code": "13.9"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Narrative Analysis", "subchapter_code": "13.10"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Discourse analysis", "subchapter_code": "13.11"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Visual analysis", "subchapter_code": "13.12"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Data display and analysis", "subchapter_code": "13.13"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Using CAQDAS", "subchapter_code": "13.14"},
    {"chapter_title": "Analysing data qualitatively", "subchapter_title": "Summary", "subchapter_code": "13.15"},

    # Chapter 14
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Introduction", "subchapter_code": "14.1"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Undertaking writing", "subchapter_code": "14.2"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Reporting approaches and report structures: an overview", "subchapter_code": "14.3"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "The traditional (academic) report structure", "subchapter_code": "14.4"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Alternative (academic) report structures", "subchapter_code": "14.5"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "The consultancy (practitioner) report", "subchapter_code": "14.6"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Ensuring clarity and accessibility", "subchapter_code": "14.7"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Developing an appropriate writing style", "subchapter_code": "14.8"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Meeting the assessment criteria", "subchapter_code": "14.9"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Writing a reflective essay or section", "subchapter_code": "14.10"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Presentations", "subchapter_code": "14.11"},
    {"chapter_title": "Writing and presenting the project report", "subchapter_title": "Summary", "subchapter_code": "14.12"},
]

